/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AdminTicket extends javax.swing.JFrame {
       Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    static class MovieItem {
    int id;
    String name;

    MovieItem(int i, String n) {
        id = i;
        name = n;
    }

    public String toString() {
        return id + " - " + name;
    }
}

static class CustomerItem {
    int id;
    String name;

    CustomerItem(int i, String n) {
        id = i;
        name = n;
    }

    public String toString() {
        return id + " - " + name;
    }
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminTicket.class.getName());

    /**
     * Creates new form AdminTicket
     */
    public AdminTicket() {
         initComponents();

    getContentPane().setBackground(UITheme.BG_DARK);
    UITheme.styleFieldLabel(jLabel1);
    UITheme.styleFieldLabel(jLabel2);
    UITheme.styleFieldLabel(jLabel3);
    UITheme.styleFieldLabel(jLabel4);
    UITheme.styleFieldLabel(jLabel5);
    UITheme.styleFieldLabel(jLabel6);
    UITheme.styleFieldLabel(jLabel7);
    UITheme.stylePrimaryButton(btnInsert);
    UITheme.styleSecondaryButton(btnEdit);
    UITheme.styleSecondaryButton(btnRead);
    UITheme.styleDangerButton(btnDelete);

    try {
        conn = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/RegDB", "db", "123");

        loadMovies();
        loadCustomers();
        btnReadActionPerformed(null);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(),
            "DB Error", JOptionPane.ERROR_MESSAGE);
    }

    tbl.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && tbl.getSelectedRow() >= 0) {

            int row = tbl.getSelectedRow();

            txtTicketID.setText(
                tbl.getValueAt(row, 0).toString());

            selectMovie(
                tbl.getValueAt(row, 1).toString());

            selectCustomer(
                tbl.getValueAt(row, 2).toString());

            txtDate.setText(
                tbl.getValueAt(row, 3).toString());

            txtTime.setText(
                tbl.getValueAt(row, 4).toString());

            txtSeat.setText(
                tbl.getValueAt(row, 5).toString());

            txtPrice.setText(
                tbl.getValueAt(row, 6).toString());
        }
    });

    cmbMovie.addActionListener(e -> loadPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnRead = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtTicketID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        cmbMovie = new javax.swing.JComboBox<>();
        cmbCustomer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Customer :");

        btnRead.setText("Read");
        btnRead.addActionListener(this::btnReadActionPerformed);

        jLabel4.setText("Date :");

        jLabel5.setText("Time :");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Movie", "Customer", "Date", "Time", "Seat", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(this::btnInsertActionPerformed);

        jLabel1.setText("ُTicket ID :");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        jLabel2.setText("Movie:");

        btnEdit.setText(" Edit ");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        jLabel6.setText("Seat :");

        jLabel7.setText("Price :");

        cmbMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cmbMovie.addActionListener(this::cmbMovieActionPerformed);

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104", "105" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTicketID, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(cmbMovie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                        .addComponent(cmbCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnInsert)
                        .addGap(55, 55, 55)
                        .addComponent(btnDelete)
                        .addGap(41, 41, 41)
                        .addComponent(btnEdit)
                        .addGap(55, 55, 55)
                        .addComponent(btnRead)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMovieActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
    try {
    stmt = conn.createStatement();

    String movie = cmbMovie.getSelectedItem().toString();
String customer = cmbCustomer.getSelectedItem().toString();

int movieID = Integer.parseInt(movie.split(" - ")[0]);
int customerID = Integer.parseInt(customer.split(" - ")[0]);

String sql = "INSERT INTO TICKETS " +
    "(TICKET_ID, MOVIE_ID, CUSTOMER_ID, SHOW_DATE, SHOW_TIME, SEAT_NO, PRICE) VALUES (" +
    txtTicketID.getText() + ", " +
    movieID + ", " +
    customerID + ", '" +
    txtDate.getText() + "', '" +
    txtTime.getText() + "', '" +
    txtSeat.getText() + "', " +
    txtPrice.getText() + ")";

    stmt.executeUpdate(sql);

    JOptionPane.showMessageDialog(null, "Ticket Added");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();

    String sql = "DELETE FROM TICKETS WHERE TICKET_ID = "
        + txtTicketID.getText();

    stmt.executeUpdate(sql);

    JOptionPane.showMessageDialog(null, "Ticket Deleted");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();
String movie = cmbMovie.getSelectedItem().toString();
String customer = cmbCustomer.getSelectedItem().toString();

int movieID = Integer.parseInt(movie.split(" - ")[0]);
int customerID = Integer.parseInt(customer.split(" - ")[0]);

   String sql = "UPDATE TICKETS SET " +
    "MOVIE_ID=" + movieID +
    ", CUSTOMER_ID=" + customerID +
    ", SHOW_DATE='" + txtDate.getText() +
    "', SHOW_TIME='" + txtTime.getText() +
    "', SEAT_NO='" + txtSeat.getText() +
    "', PRICE=" + txtPrice.getText() +
    " WHERE TICKET_ID=" + txtTicketID.getText();

    stmt.executeUpdate(sql);

    JOptionPane.showMessageDialog(null, "Ticket Updated");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();

    String sql = "SELECT * FROM TICKETS";

    rs = stmt.executeQuery(sql);

    DefaultTableModel model =
        (DefaultTableModel) tbl.getModel();

    model.setRowCount(0);

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("TICKET_ID"),
            rs.getInt("MOVIE_ID"),
            rs.getInt("CUSTOMER_ID"),
            rs.getString("SHOW_DATE"),
            rs.getString("SHOW_TIME"),
            rs.getString("SEAT_NO"),
            rs.getDouble("PRICE")
        });
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnReadActionPerformed
private void loadMovies() {
    if (conn == null)
        return;

    cmbMovie.removeAllItems();

    try {
        PreparedStatement p = conn.prepareStatement(
            "SELECT MOVIE_ID, TITLE FROM MOVIES ORDER BY MOVIE_ID");

        ResultSet r = p.executeQuery();

        while (r.next()) {
            cmbMovie.addItem(
                r.getInt("MOVIE_ID") + " - " +
                r.getString("TITLE")
            );
        }

        r.close();
        p.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}
  private void loadCustomers() {
    if (conn == null)
        return;

    cmbCustomer.removeAllItems();

    try {
        PreparedStatement p = conn.prepareStatement(
            "SELECT CUSTOMER_ID, NAME FROM CUSTOMERS ORDER BY CUSTOMER_ID");

        ResultSet r = p.executeQuery();

        while (r.next()) {
            cmbCustomer.addItem(
                r.getInt("CUSTOMER_ID") + " - " +
                r.getString("NAME")
            );
        }

        r.close();
        p.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}
  private void loadPrice() {

    if (cmbMovie.getSelectedItem() == null) {
        txtPrice.setText("");
        return;
    }

    try {
        String selected = cmbMovie.getSelectedItem().toString();

        int movieID = Integer.parseInt(
            selected.split(" - ")[0]
        );

        PreparedStatement p = conn.prepareStatement(
            "SELECT PRICE FROM MOVIES WHERE MOVIE_ID=?");

        p.setInt(1, movieID);

        ResultSet r = p.executeQuery();

        if (r.next()) {
            txtPrice.setText(
                String.valueOf(r.getDouble("PRICE")));
        }

        r.close();
        p.close();

    } catch (Exception e) {
        txtPrice.setText("");
    }
}
  private void selectMovie(String value) {

    for (int i = 0; i < cmbMovie.getItemCount(); i++) {

        String movie = cmbMovie.getItemAt(i);

        if (movie.startsWith(value + " - ")) {
            cmbMovie.setSelectedIndex(i);
            break;
        }
    }
}
  private void selectCustomer(String value) {

    for (int i = 0; i < cmbCustomer.getItemCount(); i++) {

        String customer = cmbCustomer.getItemAt(i);

        if (customer.startsWith(value + " - ")) {
            cmbCustomer.setSelectedIndex(i);
            break;
        }
    }
}
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminTicket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRead;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTextField txtTicketID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
