/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;


public class AdminMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMenu.class.getName());

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();

        getContentPane().setBackground(UITheme.BG_DARK);
        UITheme.styleHeading(jLabel2);
        UITheme.styleSecondaryButton(btnMovie);
        UITheme.styleSecondaryButton(btnCustomer);
        UITheme.styleSecondaryButton(btnTicket);
        UITheme.styleSecondaryButton(btnMovieSearch);
        UITheme.styleSecondaryButton(btnCustomerTicket);
        UITheme.styleDangerButton(btnLogout);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMovie = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnMovieSearch = new javax.swing.JButton();
        btnCustomerTicket = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMovie.setText("Movies");
        btnMovie.addActionListener(this::btnMovieActionPerformed);

        btnCustomer.setText("Customers");
        btnCustomer.addActionListener(this::btnCustomerActionPerformed);

        btnTicket.setText("Tickets");
        btnTicket.addActionListener(this::btnTicketActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnMovieSearch.setText("Movie Search");
        btnMovieSearch.addActionListener(this::btnMovieSearchActionPerformed);

        btnCustomerTicket.setText("Customer Tickets");
        btnCustomerTicket.addActionListener(this::btnCustomerTicketActionPerformed);

        jLabel2.setText("Cinema Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(btnCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(btnMovie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(btnMovieSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCustomerTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(207, 207, 207))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(btnMovie)
                .addGap(18, 18, 18)
                .addComponent(btnCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMovieSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCustomerTicket)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieActionPerformed
        // TODO add your handling code here:
        AdminMovie frm = new AdminMovie();
frm.show();
    }//GEN-LAST:event_btnMovieActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        AdminCustomer frm = new AdminCustomer();
frm.show();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // TODO add your handling code here:
        AdminTicket frm = new AdminTicket();
frm.show();
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login frm = new Login();
frm.show();
dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMovieSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieSearchActionPerformed
        // TODO add your handling code here:
        MovieSearch frm = new MovieSearch(0);
frm.show();
    }//GEN-LAST:event_btnMovieSearchActionPerformed

    private void btnCustomerTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerTicketActionPerformed
        // TODO add your handling code here:
        SearchCustomerTicket frm = new SearchCustomerTicket();
frm.show();
    }//GEN-LAST:event_btnCustomerTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnCustomerTicket;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMovie;
    private javax.swing.JButton btnMovieSearch;
    private javax.swing.JButton btnTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
