/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AdminCustomer extends javax.swing.JFrame {
    Connection conn = null;
Statement stmt = null;
ResultSet rs = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminCustomer.class.getName());

    /**
     * Creates new form AdminCustomer
     */
    public AdminCustomer() {
         initComponents();
            getContentPane().setBackground(UITheme.BG_DARK);
    UITheme.styleFieldLabel(jLabel1);
    UITheme.styleFieldLabel(jLabel2);
    UITheme.styleFieldLabel(jLabel3);
    UITheme.styleFieldLabel(jLabel4);
    UITheme.stylePrimaryButton(btnInsert);
    UITheme.styleSecondaryButton(btnEdit);
    UITheme.styleSecondaryButton(btnRead);
    UITheme.styleSecondaryButton(btnClear);
    UITheme.styleDangerButton(btnDelete);
            try { 
        conn = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/RegDB", "db", "123");

        btnReadActionPerformed(null);

    } 
    catch (Exception ex) { 
        JOptionPane.showMessageDialog(null, ex.getMessage(),
            "DB Error", JOptionPane.ERROR_MESSAGE); 
    }
            tbl.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && tbl.getSelectedRow() >= 0) {

            int row = tbl.getSelectedRow();

            txtCustomerID.setText(tbl.getValueAt(row, 0).toString());
            txtName.setText(tbl.getValueAt(row, 1).toString());
            txtPhone.setText(tbl.getValueAt(row, 2).toString());
            txtEmail.setText(tbl.getValueAt(row, 3).toString());
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnRead = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtCustomerID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Phone :");

        btnRead.setText("Read");
        btnRead.addActionListener(this::btnReadActionPerformed);

        jLabel4.setText("Email :");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        txtCustomerID.addActionListener(this::txtCustomerIDActionPerformed);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(this::btnInsertActionPerformed);

        jLabel1.setText("Customer ID :");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        jLabel2.setText("Name :");

        btnEdit.setText(" Edit ");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnClear.setText("clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                        .addComponent(txtPhone)
                                        .addComponent(txtName))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnInsert)
                        .addGap(55, 55, 55)
                        .addComponent(btnDelete)
                        .addGap(41, 41, 41)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnRead)
                    .addComponent(btnClear))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIDActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
         if (txtCustomerID.getText().isEmpty() ||
        txtName.getText().isEmpty() ||
        txtPhone.getText().isEmpty() ||
        txtEmail.getText().isEmpty()) {

        JOptionPane.showMessageDialog(null, "Please fill all fields");
        return;
    }
        try {
    stmt = conn.createStatement();

    String sql = "INSERT INTO CUSTOMERS " +
        "(CUSTOMER_ID, NAME, PHONE, EMAIL) VALUES (" +
        txtCustomerID.getText() + ", '" +
        txtName.getText() + "', '" +
        txtPhone.getText() + "', '" +
        txtEmail.getText() + "')";

    stmt.executeUpdate(sql);
    btnReadActionPerformed(null);

    JOptionPane.showMessageDialog(null, "Customer Added");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (txtCustomerID.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Enter Customer ID");
    return;
}
        try {
    stmt = conn.createStatement();

    String sql = "DELETE FROM CUSTOMERS WHERE CUSTOMER_ID = "
        + txtCustomerID.getText();

    stmt.executeUpdate(sql);
    btnReadActionPerformed(null);
btnClearActionPerformed(null);

    JOptionPane.showMessageDialog(null, "Customer Deleted");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();

    String sql = "UPDATE CUSTOMERS SET NAME='" +
        txtName.getText() + "', PHONE='" +
        txtPhone.getText() + "', EMAIL='" +
        txtEmail.getText() + "' WHERE CUSTOMER_ID=" +
        txtCustomerID.getText();

    stmt.executeUpdate(sql);
    btnReadActionPerformed(null);
    

    JOptionPane.showMessageDialog(null, "Customer Updated");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();

    String sql = "SELECT * FROM CUSTOMERS";

    rs = stmt.executeQuery(sql);

    DefaultTableModel model =
        (DefaultTableModel) tbl.getModel();

    model.setRowCount(0);

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("CUSTOMER_ID"),
            rs.getString("NAME"),
            rs.getString("PHONE"),
            rs.getString("EMAIL")
        });
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtCustomerID.setText("");
    txtName.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    tbl.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
