/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 package cinemaproject;
 import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AdminMovie extends javax.swing.JFrame {
Connection conn = null;
Statement stmt = null;
ResultSet rs = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMovie.class.getName());

    /**
     * Creates new form AdminMovie
     */
    public AdminMovie() {
         initComponents();

    getContentPane().setBackground(UITheme.BG_DARK);
    UITheme.styleFieldLabel(jLabel1);
    UITheme.styleFieldLabel(jLabel2);
    UITheme.styleFieldLabel(jLabel3);
    UITheme.styleFieldLabel(jLabel4);
    UITheme.styleFieldLabel(jLabel5);
    UITheme.styleFieldLabel(jLabel6);
    UITheme.stylePrimaryButton(btnInsert);
    UITheme.styleSecondaryButton(btnEdit);
    UITheme.styleSecondaryButton(btnRead);
    UITheme.styleSecondaryButton(btnClear);
    UITheme.styleDangerButton(btnDelete);

    try {
        conn = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/RegDB", "db", "123");


    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(),
            "DB Error", JOptionPane.ERROR_MESSAGE);
    }

    tbl.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && tbl.getSelectedRow() >= 0) {

            int row = tbl.getSelectedRow();

            txtMovieID.setText(tbl.getValueAt(row, 0).toString());
            txtTitle.setText(tbl.getValueAt(row, 1).toString());
            txtGenre.setText(tbl.getValueAt(row, 2).toString());
            txtDuration.setText(tbl.getValueAt(row, 3).toString());
            txtRating.setText(tbl.getValueAt(row, 4).toString());
            txtPrice.setText(tbl.getValueAt(row, 5).toString());
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Movie ID :");

        jLabel2.setText("Title :");

        jLabel3.setText("Genre :");

        jLabel4.setText("Duration :");

        jLabel5.setText("Rating :");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(this::btnInsertActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdit.setText(" Edit ");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnRead.setText("Read");
        btnRead.addActionListener(this::btnReadActionPerformed);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Genre", "Duration", "Rating ", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
            tbl.getColumnModel().getColumn(2).setResizable(false);
            tbl.getColumnModel().getColumn(3).setResizable(false);
            tbl.getColumnModel().getColumn(4).setResizable(false);
            tbl.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel6.setText("Price :");

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMovieID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtDuration, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGenre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRating, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnInsert)
                        .addGap(55, 55, 55)
                        .addComponent(btnDelete)
                        .addGap(41, 41, 41)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnRead)
                    .addComponent(btnClear))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
          if (txtMovieID.getText().isEmpty() ||
    txtTitle.getText().isEmpty() ||
    txtGenre.getText().isEmpty() ||
    txtDuration.getText().isEmpty() ||
    txtRating.getText().isEmpty() ||
    txtPrice.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Please fill all fields");
    return;
} 
        try {
        stmt = conn.createStatement();

        String sql = "INSERT INTO MOVIES " +
    "(MOVIE_ID, TITLE, GENRE, DURATION, RATING, PRICE) VALUES (" +
    txtMovieID.getText() + ", '" +
    txtTitle.getText() + "', '" +
    txtGenre.getText() + "', " +
    txtDuration.getText() + ", " +
    txtRating.getText() + ", " +
    txtPrice.getText() + ")";
        stmt.executeUpdate(sql);
        btnReadActionPerformed(null);
btnClearActionPerformed(null);

        JOptionPane.showMessageDialog(null, "Movie Added");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();

  String sql = "DELETE FROM MOVIES WHERE MOVIE_ID = "
    + txtMovieID.getText();

    stmt.executeUpdate(sql);

    JOptionPane.showMessageDialog(null, "Movie Deleted");
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
    stmt = conn.createStatement();

   String sql = "UPDATE MOVIES SET TITLE='"
    + txtTitle.getText() + "', GENRE='"
    + txtGenre.getText() + "', DURATION="
    + txtDuration.getText() + ", RATING="
    + txtRating.getText() + ", PRICE="
    + txtPrice.getText() + " WHERE MOVIE_ID="
    + txtMovieID.getText();

    stmt.executeUpdate(sql);
btnReadActionPerformed(null);
    JOptionPane.showMessageDialog(null, "Movie Updated");
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
       
   try {
        stmt = conn.createStatement();

        // Get movie by ID and fill the fields
        if (!txtMovieID.getText().isEmpty()) {

            String sql = "SELECT * FROM MOVIES WHERE MOVIE_ID = "
                    + txtMovieID.getText();

            rs = stmt.executeQuery(sql);

            if (rs.next()) {
                txtTitle.setText(rs.getString("TITLE"));
                txtGenre.setText(rs.getString("GENRE"));
                txtDuration.setText(rs.getString("DURATION"));
                txtRating.setText(rs.getString("RATING"));
                txtPrice.setText(rs.getString("PRICE"));
            } else {
                JOptionPane.showMessageDialog(null, "Movie not found");
            }
        }

        // Show all movies in the table
        String sql2 = "SELECT * FROM MOVIES";
        rs = stmt.executeQuery(sql2);

        DefaultTableModel model =
                (DefaultTableModel) tbl.getModel();

        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("MOVIE_ID"),
                rs.getString("TITLE"),
                rs.getString("GENRE"),
                rs.getInt("DURATION"),
                rs.getDouble("RATING"),
                rs.getDouble("PRICE")
            });
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMovieID.setText("");
txtTitle.setText("");
txtGenre.setText("");
txtDuration.setText("");
txtRating.setText("");
txtPrice.setText("");
tbl.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMovie().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtMovieID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
