/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.text.SimpleDateFormat;
import java.util.Date;


public class BookTicket extends javax.swing.JFrame {

    private final int customerID;
    private final String movieTitle;

    /**
     * Creates new form BookTicket
     */
    public BookTicket(int customerID, String movieTitle) {
        this.customerID = customerID;
        this.movieTitle = movieTitle;
        initComponents();
        setTitle("Book Ticket");
        setLocationRelativeTo(null);
        lblMovieValue.setText(movieTitle);
            loadPrice();

        getContentPane().setBackground(UITheme.BG_DARK);
        UITheme.styleHeading(lblTitle);
        UITheme.styleFieldLabel(lblMovieCaption);
        UITheme.styleFieldLabel(lblDate);
        UITheme.styleFieldLabel(lblTime);
        UITheme.styleFieldLabel(lblSeat);
        UITheme.styleFieldLabel(lblPrice);
        lblMovieValue.setForeground(UITheme.BURGUNDY_LIGHT);
        lblMovieValue.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        UITheme.stylePrimaryButton(btnConfirm);
        UITheme.styleSecondaryButton(btnCalendar);
        UITheme.styleLinkButton(btnCancel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMovieCaption = new javax.swing.JLabel();
        lblMovieValue = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCalendar = new javax.swing.JButton();
        cmbTime = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTitle.setText("Book Your Ticket");

        lblMovieCaption.setText("Movie:");

        lblMovieValue.setText("Movie Title");

        lblDate.setText("Show Date (YYYY-MM-DD):");

        lblTime.setText("Show Time (HH:MM):");

        lblSeat.setText("Seat Number:");

        lblPrice.setText("Price:");

        btnConfirm.setText("Confirm Booking");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnCalendar.setText("Calendar");
        btnCalendar.addActionListener(this::btnCalendarActionPerformed);

        cmbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "15:00", "18:00", "21:00" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnConfirm)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMovieCaption)
                            .addComponent(lblDate)
                            .addComponent(lblTime)
                            .addComponent(lblSeat)
                            .addComponent(lblPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalendar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMovieValue, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(txtSeat, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(cmbTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovieCaption)
                    .addComponent(lblMovieValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalendar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime)
                    .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeat)
                    .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void loadPrice() {
    String title = movieTitle;

    try (Connection conn = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/RegDB", "db", "123");
         PreparedStatement stmt = conn.prepareStatement(
            "SELECT PRICE FROM MOVIES WHERE TITLE = ?")) {

        stmt.setString(1, title);

        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                txtPrice.setText(String.valueOf(rs.getDouble("PRICE")));
            }
        }

    } catch (Exception ex) {
        txtPrice.setText("");
    }
}

private void chooseDate() {
    JSpinner spinner = new JSpinner(
        new SpinnerDateModel(new Date(), null, null, java.util.Calendar.DAY_OF_MONTH)
    );

    spinner.setEditor(
        new JSpinner.DateEditor(spinner, "yyyy-MM-dd")
    );

    if (JOptionPane.showConfirmDialog(
            this,
            spinner,
            "Select Show Date",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {

        txtDate.setText(
            new SimpleDateFormat("yyyy-MM-dd")
                .format((Date) spinner.getValue())
        );
    }
}

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String showDate = txtDate.getText().trim();
String showTime = cmbTime.getSelectedItem().toString();
String seatNo = txtSeat.getText().trim();
String priceText = txtPrice.getText().trim();

if (showDate.isEmpty() || showTime.isEmpty() || seatNo.isEmpty() || priceText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields.",
        "Missing info", JOptionPane.WARNING_MESSAGE);
    return;
}

double price;

try {
    price = Double.parseDouble(priceText);

    if (price <= 0) {
        throw new NumberFormatException();
    }

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Price must be a number.",
        "Invalid price", JOptionPane.WARNING_MESSAGE);
    return;
}

try (Connection conn = DriverManager.getConnection(
        "jdbc:derby://localhost:1527/RegDB", "db", "123")) {

    // Get MOVIE_ID
    int movieID;

    try (PreparedStatement findMovie = conn.prepareStatement(
            "SELECT MOVIE_ID FROM MOVIES WHERE TITLE = ?")) {

        findMovie.setString(1, movieTitle);

        try (ResultSet rs = findMovie.executeQuery()) {

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this,
                    "Movie not found.",
                    "Movie Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            movieID = rs.getInt("MOVIE_ID");
        }
    }

    // Check if seat is already booked
    try (PreparedStatement checkSeat = conn.prepareStatement(
            "SELECT TICKET_ID FROM TICKETS "
            + "WHERE MOVIE_ID = ? "
            + "AND SHOW_DATE = ? "
            + "AND SHOW_TIME = ? "
            + "AND SEAT_NO = ?")) {

        checkSeat.setInt(1, movieID);
        checkSeat.setString(2, showDate);
        checkSeat.setString(3, showTime);
        checkSeat.setString(4, seatNo);

        try (ResultSet rs = checkSeat.executeQuery()) {

            if (rs.next()) {
                JOptionPane.showMessageDialog(this,
                    "This seat is already booked.",
                    "Seat Unavailable",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }

    // Generate new Ticket ID
    int newTicketID = 1;

    try (PreparedStatement maxID = conn.prepareStatement(
            "SELECT MAX(TICKET_ID) AS MAXID FROM TICKETS");
         ResultSet rs = maxID.executeQuery()) {

        if (rs.next()) {
            newTicketID = rs.getInt("MAXID") + 1;
        }
    }

    // Insert ticket
    try (PreparedStatement insert = conn.prepareStatement(
            "INSERT INTO TICKETS "
            + "(TICKET_ID, MOVIE_ID, CUSTOMER_ID, SHOW_DATE, "
            + "SHOW_TIME, SEAT_NO, PRICE) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?)")) {

        insert.setInt(1, newTicketID);
        insert.setInt(2, movieID);
        insert.setInt(3, customerID);
        insert.setString(4, showDate);
        insert.setString(5, showTime);
        insert.setString(6, seatNo);
        insert.setDouble(7, price);

        int n = insert.executeUpdate();

        if (n > 0) {
            JOptionPane.showMessageDialog(this,
                "Ticket booked! Your ticket number is " + newTicketID,
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

            dispose();
        }
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this,
        ex.getMessage(),
        "Booking Error",
        JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarActionPerformed
        // TODO add your handling code here:
        chooseDate();
    }//GEN-LAST:event_btnCalendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();
        java.awt.EventQueue.invokeLater(() -> new BookTicket(1, "Avatar").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMovieCaption;
    private javax.swing.JLabel lblMovieValue;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeat;
    // End of variables declaration//GEN-END:variables
}
