/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;
import javax.swing.JOptionPane;

public class CustomerMenu extends javax.swing.JFrame {
    
    int customerID;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerMenu.class.getName());

    /**
     * Creates new form CustomerMenu
     */
   public CustomerMenu(int customerID) {
    this.customerID = customerID;

        initComponents();

        setTitle("Customer Menu");
        setLocationRelativeTo(null);

        getContentPane().setBackground(UITheme.BG_DARK);

        UITheme.styleSecondaryButton(btnProfile);
        UITheme.styleSecondaryButton(btnTickets);
        UITheme.styleSecondaryButton(btnMovieSearch);
        UITheme.styleDangerButton(btnLogout);
    }

    public CustomerMenu() {
        this(0);}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnMovieSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CUSTOMER MENU");

        btnProfile.setText("Profile");
        btnProfile.addActionListener(this::btnProfileActionPerformed);

        btnTickets.setText("My Tickets");
        btnTickets.addActionListener(this::btnTicketsActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnMovieSearch.setText("Movie Search");
        btnMovieSearch.addActionListener(this::btnMovieSearchActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTickets, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(btnMovieSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(btnProfile)
                .addGap(29, 29, 29)
                .addComponent(btnTickets)
                .addGap(18, 18, 18)
                .addComponent(btnMovieSearch)
                .addGap(26, 26, 26)
                .addComponent(btnLogout)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    new CustomerProfile(customerID).setVisible(true);
    dispose();

    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        // TODO add your handling code here:
         new CustomerTicketInfo(customerID).setVisible(true);
    dispose();
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
      
    if (JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        new Login().setVisible(true);
        dispose();
    }
    
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMovieSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieSearchActionPerformed
        // TODO add your handling code here:
new MovieSearch(customerID).setVisible(true);
dispose();
    }//GEN-LAST:event_btnMovieSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMovieSearch;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnTickets;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
