/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;
import javax.swing.JOptionPane;

public class HomePage extends javax.swing.JFrame {

    private int customerID;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    public HomePage() {
        this(0);
    }

   
    public HomePage(int customerID) {
          this.customerID = customerID;
    initComponents();

    setTitle("Cinema Project");
    setLocationRelativeTo(null);

    lblAvatarImage.setText("");
    lblTitanicImage.setText("");
    lblInceptionImage.setText("");
    lblLionKingImage.setText("");
    lblInterstellarImage.setText("");
    lblJokerImage.setText("");

    getContentPane().setBackground(UITheme.BG_DARK);
   
    UITheme.styleHeading(jLabel1);

    javax.swing.JLabel[] titles = {lblAvatarTitle, lblTitanicTitle, lblInceptionTitle,
        lblLionKingTitle, lblInterstellarTitle, lblJokerTitle};
    javax.swing.JLabel[] genres = {lblAvatarGenre, lblTitanicGenre, lblInceptionGenre,
        lblLionKingGenre, lblInterstellarGenre, lblJokerGenre};
    javax.swing.JLabel[] ratings = {lblAvatarRating, lblTitanicRating, lblInceptionRating,
        lblLionKingRating, lblInterstellarRating, lblJokerRating};
    javax.swing.JButton[] bookButtons = {btnAvatar, btnTitanic, btnInception,
        btnLionKing, btnInterstellar, btnJoker};

    for (javax.swing.JLabel t : titles) {
        t.setForeground(UITheme.CREAM);
        t.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    }
    for (javax.swing.JLabel g : genres) {
        UITheme.styleCaption(g);
    }
    for (javax.swing.JLabel r : ratings) {
        r.setForeground(UITheme.BURGUNDY_LIGHT);
    }
    for (javax.swing.JButton b : bookButtons) {
        UITheme.stylePrimaryButton(b);
    }

javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(getContentPane());
setContentPane(scrollPane);
    setupAccountMenuBar();
    }

    
    private void setupAccountMenuBar() {
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();

        javax.swing.JMenuItem accountItem = new javax.swing.JMenuItem("My Account");
        accountItem.addActionListener(e -> {
            new CustomerMenu(customerID).setVisible(true);
            dispose();
        });

        javax.swing.JMenuItem logoutItem = new javax.swing.JMenuItem("Logout");
        logoutItem.addActionListener(e -> {
            new Login().setVisible(true);
            dispose();
        });

        menuBar.add(accountItem);
        menuBar.add(logoutItem);
        setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAvatarImage = new javax.swing.JLabel();
        lblAvatarTitle = new javax.swing.JLabel();
        lblAvatarGenre = new javax.swing.JLabel();
        lblAvatarRating = new javax.swing.JLabel();
        btnAvatar = new javax.swing.JButton();
        lblLionKingImage = new javax.swing.JLabel();
        lblLionKingTitle = new javax.swing.JLabel();
        lblLionKingGenre = new javax.swing.JLabel();
        lblLionKingRating = new javax.swing.JLabel();
        btnLionKing = new javax.swing.JButton();
        lblInterstellarImage = new javax.swing.JLabel();
        lblInterstellarTitle = new javax.swing.JLabel();
        lblTitanicTitle = new javax.swing.JLabel();
        lblTitanicGenre = new javax.swing.JLabel();
        lblTitanicRating = new javax.swing.JLabel();
        btnTitanic = new javax.swing.JButton();
        lblInterstellarGenre = new javax.swing.JLabel();
        lblInterstellarRating = new javax.swing.JLabel();
        btnInterstellar = new javax.swing.JButton();
        lblTitanicImage = new javax.swing.JLabel();
        lblInceptionTitle = new javax.swing.JLabel();
        lblJokerTitle = new javax.swing.JLabel();
        lblJokerGenre = new javax.swing.JLabel();
        lblJokerRating = new javax.swing.JLabel();
        btnJoker = new javax.swing.JButton();
        lblInceptionGenre = new javax.swing.JLabel();
        lblInceptionRating = new javax.swing.JLabel();
        btnInception = new javax.swing.JButton();
        lblJokerImage = new javax.swing.JLabel();
        lblInceptionImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cinema ");

        lblAvatarImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.jpeg"))); // NOI18N
        lblAvatarImage.setText("jLabel2");

        lblAvatarTitle.setText("Avatar");

        lblAvatarGenre.setText("Action    ");

        lblAvatarRating.setText(" ⭐ 8.5  ");

        btnAvatar.setText("Book Ticket");
        btnAvatar.addActionListener(this::btnAvatarActionPerformed);

        lblLionKingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thelionking.jpeg"))); // NOI18N
        lblLionKingImage.setText("jLabel2");

        lblLionKingTitle.setText("The Lion King");

        lblLionKingGenre.setText("Animation    ");

        lblLionKingRating.setText(" ⭐ 8.5  ");

        btnLionKing.setText("Book Ticket");
        btnLionKing.addActionListener(this::btnLionKingActionPerformed);

        lblInterstellarImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interstellar.jpeg"))); // NOI18N
        lblInterstellarImage.setText("jLabel2");

        lblInterstellarTitle.setText("Intersteller");

        lblTitanicTitle.setText("Titanic");

        lblTitanicGenre.setText("Romance");

        lblTitanicRating.setText("⭐ 7.9");

        btnTitanic.setText("Book Ticket");
        btnTitanic.addActionListener(this::btnTitanicActionPerformed);

        lblInterstellarGenre.setText("Sci-Fi");

        lblInterstellarRating.setText("⭐ 8.7");

        btnInterstellar.setText("Book Ticket");
        btnInterstellar.addActionListener(this::btnInterstellarActionPerformed);

        lblTitanicImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titanic.jpeg"))); // NOI18N
        lblTitanicImage.setText("jLabel2");

        lblInceptionTitle.setText("Inception");

        lblJokerTitle.setText("Joker");

        lblJokerGenre.setText("Drama");

        lblJokerRating.setText("⭐ 8.4");

        btnJoker.setText("Book Ticket");
        btnJoker.addActionListener(this::btnJokerActionPerformed);

        lblInceptionGenre.setText("Sci-Fi");

        lblInceptionRating.setText(" ⭐ 8.8");

        btnInception.setText("Book Ticket");
        btnInception.addActionListener(this::btnInceptionActionPerformed);

        lblJokerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/joker.jpeg"))); // NOI18N
        lblJokerImage.setText("jLabel2");

        lblInceptionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inception.jpeg"))); // NOI18N
        lblInceptionImage.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInterstellarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitanicImage, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvatar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvatarRating, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAvatarGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAvatarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblLionKingRating))
                            .addComponent(btnLionKing)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLionKingGenre)
                            .addComponent(lblLionKingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInceptionImage, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblJokerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvatarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblLionKingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addComponent(lblInceptionGenre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(btnInception))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblInceptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblInceptionRating))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(305, 305, 305)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(lblJokerRating))
                                            .addComponent(btnJoker)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(321, 321, 321)
                                        .addComponent(lblJokerGenre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(329, 329, 329)
                                        .addComponent(lblJokerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblInterstellarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(lblInterstellarGenre))
                                            .addComponent(lblInterstellarRating)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(btnInterstellar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(320, 320, 320)
                                        .addComponent(lblTitanicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(314, 314, 314)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitanicRating)
                                            .addComponent(lblTitanicGenre)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(301, 301, 301)
                                        .addComponent(btnTitanic))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel1)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvatarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLionKingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvatarTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvatarGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvatarRating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAvatar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLionKingTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLionKingGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLionKingRating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLionKing)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterstellarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitanicImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInterstellarTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInterstellarGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInterstellarRating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInterstellar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitanicTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitanicGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitanicRating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTitanic)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInceptionImage, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJokerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInceptionTitle)
                            .addComponent(lblJokerTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInceptionGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInceptionRating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInception))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblJokerGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJokerRating, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJoker)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatarActionPerformed
        new BookTicket(customerID, "Avatar").setVisible(true);
    }//GEN-LAST:event_btnAvatarActionPerformed

    private void btnLionKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLionKingActionPerformed
        new BookTicket(customerID, "The Lion King").setVisible(true);
    }//GEN-LAST:event_btnLionKingActionPerformed

    private void btnInceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInceptionActionPerformed
        new BookTicket(customerID, "Inception").setVisible(true);
    }//GEN-LAST:event_btnInceptionActionPerformed

    private void btnJokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJokerActionPerformed
        new BookTicket(customerID, "Joker").setVisible(true);
    }//GEN-LAST:event_btnJokerActionPerformed

    private void btnInterstellarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterstellarActionPerformed
        new BookTicket(customerID, "Interstellar").setVisible(true);
    }//GEN-LAST:event_btnInterstellarActionPerformed

    private void btnTitanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitanicActionPerformed
        new BookTicket(customerID, "Titanic").setVisible(true);
    }//GEN-LAST:event_btnTitanicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvatar;
    private javax.swing.JButton btnInception;
    private javax.swing.JButton btnInterstellar;
    private javax.swing.JButton btnJoker;
    private javax.swing.JButton btnLionKing;
    private javax.swing.JButton btnTitanic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAvatarGenre;
    private javax.swing.JLabel lblAvatarImage;
    private javax.swing.JLabel lblAvatarRating;
    private javax.swing.JLabel lblAvatarTitle;
    private javax.swing.JLabel lblInceptionGenre;
    private javax.swing.JLabel lblInceptionImage;
    private javax.swing.JLabel lblInceptionRating;
    private javax.swing.JLabel lblInceptionTitle;
    private javax.swing.JLabel lblInterstellarGenre;
    private javax.swing.JLabel lblInterstellarImage;
    private javax.swing.JLabel lblInterstellarRating;
    private javax.swing.JLabel lblInterstellarTitle;
    private javax.swing.JLabel lblJokerGenre;
    private javax.swing.JLabel lblJokerImage;
    private javax.swing.JLabel lblJokerRating;
    private javax.swing.JLabel lblJokerTitle;
    private javax.swing.JLabel lblLionKingGenre;
    private javax.swing.JLabel lblLionKingImage;
    private javax.swing.JLabel lblLionKingRating;
    private javax.swing.JLabel lblLionKingTitle;
    private javax.swing.JLabel lblTitanicGenre;
    private javax.swing.JLabel lblTitanicImage;
    private javax.swing.JLabel lblTitanicRating;
    private javax.swing.JLabel lblTitanicTitle;
    // End of variables declaration//GEN-END:variables
}
