/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;

import java.sql.*; 
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    Connection conn = null; 
    Statement stmt = null;
    ResultSet rs = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Cinema Tickets System");
    setLocationRelativeTo(null);
    getRootPane().setDefaultButton(btnLogin);

    getContentPane().setBackground(UITheme.BG_DARK);
    UITheme.styleHeading(jLabel1);
    UITheme.styleFieldLabel(jLabel2);
    UITheme.styleFieldLabel(jLabel3);
    UITheme.stylePrimaryButton(btnLogin);
    UITheme.styleLinkButton(btnNewUser);

     try {
        

        conn = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/RegDB",
            "db",
            "123"
        );

        JOptionPane.showMessageDialog(
            null,
            "Connected",
            "DB",
            JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(
            null,
            "Connection Error:\n" + ex.toString(),
            "DB",
            JOptionPane.ERROR_MESSAGE
        );

        ex.printStackTrace();
    }
    }
    /**  
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnNewUser = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        jLabel1.setText("Cinema Tickets System");

        jLabel2.setText("Username :");

        jLabel3.setText("Password:");

        btnNewUser.setText("New User ?");
        btnNewUser.addActionListener(this::btnNewUserActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(btnNewUser))
                            .addComponent(txtPass))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnNewUser))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
         String username = txtUser.getText();
String password = new String(txtPass.getPassword());
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Please enter username and password.",
            "Validation",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try
    {
        stmt = conn.createStatement();
           String sql = "SELECT * FROM \"DB\".USERS WHERE USERNAME ='"
    + username + "' AND PASSWORD='"+password+"'";
   
    rs = stmt.executeQuery(sql);


    if (rs.next())
    {
        String role = rs.getString("ROLE");

        if (role.equalsIgnoreCase("ADMIN"))
        {
            AdminMenu frm = new AdminMenu();
            frm.show();
        }
        else
        {
            int customerID = rs.getInt("CUSTOMER_ID");

    if (rs.wasNull()) {
        JOptionPane.showMessageDialog(
            this,
            "This account is not linked to a customer.",
            "Login Error",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    HomePage frm = new HomePage(customerID);
    frm.show();
        }

        dispose();
    }
    else
    {
        JOptionPane.showMessageDialog(
            null, "Invalid username or password",
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}
catch (Exception ex)
{
    JOptionPane.showMessageDialog(
        null, ex.getMessage(),
        "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        // TODO add your handling code here:
    new NewUser().setVisible(true);
    }//GEN-LAST:event_btnNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    UITheme.installLookAndFeel();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
     }
