/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemaproject;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SearchCustomerTicket extends javax.swing.JFrame {
    Connection conn = null;
Statement stmt = null;
ResultSet rs = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchCustomerTicket.class.getName());

    /**
     * Creates new form SearchCustomerTicket
     */
    public SearchCustomerTicket() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(UITheme.BG_DARK);
        UITheme.styleHeading(jLabel1);
        UITheme.styleFieldLabel(jLabel2);
        UITheme.stylePrimaryButton(btnSearch);
        try {
        conn = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/RegDB", "db", "123");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(),
            "DB Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CUSTOMER TICKET SEARCH");

        jLabel2.setText("Customer ID :");

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Movie", "Customer", "Date", "Time", "Seat", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
             String text = jTextField1.getText().trim();

        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "Please enter Customer ID.",
                "Validation",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int customerID;

        try {
            customerID = Integer.parseInt(text);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                null,
                "Customer ID must be a number.",
                "Validation",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            stmt = conn.createStatement();

            String sql =
                "SELECT T.TICKET_ID, M.TITLE, C.NAME, " +
                "T.SHOW_DATE, T.SHOW_TIME, T.SEAT_NO, T.PRICE " +
                "FROM TICKETS T " +
                "JOIN MOVIES M ON T.MOVIE_ID = M.MOVIE_ID " +
                "JOIN CUSTOMERS C ON T.CUSTOMER_ID = C.CUSTOMER_ID " +
                "WHERE T.CUSTOMER_ID = " + customerID;

            rs = stmt.executeQuery(sql);

            DefaultTableModel model =
                (DefaultTableModel) tbl.getModel();

            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("TICKET_ID"),
                    rs.getString("TITLE"),
                    rs.getString("NAME"),
                    rs.getString("SHOW_DATE"),
                    rs.getString("SHOW_TIME"),
                    rs.getString("SEAT_NO"),
                    rs.getDouble("PRICE")
                });
            }

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(
                    null,
                    "No tickets found.",
                    "Search",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                null,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UITheme.installLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchCustomerTicket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
